spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - SetResponseHeader=Access-Control-Allow-Origin,${cors.config.origins}
      routes:
        - id: preduzece
          uri: lb://preduzece
          predicates:
            - Path=/api/preduzece/**, /api/koeficijenti/**, /api/zaposleni/**, /api/plata/**, /api/obracun_zarade/**, /api/obracun/**, /api/obracun_zarade_config/**, /api/obracun_zaposleni/**
        - id: knjizenje
          uri: lb://knjizenje
          predicates:
            - Path=/api/konto/**, /api/bilans/**, /api/glavna-knjiga/**, /api/faktura/**, /api/knjizenje/**, /api/izvestaji/**, /api/transakcije/**, /api/sifraTransakcije/**, /api/troskovni-centri/** , /api/profitni-centri/**, /api/povracaji/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/permissions/**, /api/users/**, /auth/**
        - id: nabavka
          uri: lb://nabavka
          predicates:
            - Path=/api/artikli/**, /api/kalkulacije/**, /api/konverzije/**, /api/lokacije/**, /api/troskovi/**
  application:
    name: gateway
  main:
    web-application-type: reactive

server:
  port: 8080

cors:
  config:
    origins: http://localhost:4200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
