name: Docker build and push

on:
  push:
    branches:
      - 'develop'

# Ogranicava da samo jedan job moze da bude pokrenut u isto vreme
concurrency: ci-${{ github.ref }}

jobs:
  docker-build-push:
    name: Build and push latest images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push racunovodstvo-eureka image
        uses: docker/build-push-action@v2
        with:
          context: ./eureka
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/racunovodstvo-eureka:dev

      - name: Build and Push racunovodstvo-gateway image
        uses: docker/build-push-action@v2
        with:
          context: ./gateway
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/racunovodstvo-gateway:dev

      - name: Build and Push racunovodstvo-knjizenje image
        uses: docker/build-push-action@v2
        with:
          context: ./knjizenje
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/racunovodstvo-knjizenje:dev

      - name: Build and Push racunovodstvo-nabavka image
        uses: docker/build-push-action@v2
        with:
          context: ./nabavka
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/racunovodstvo-nabavka:dev

      - name: Build and Push racunovodstvo-preduzece image
        uses: docker/build-push-action@v2
        with:
          context: ./preduzece
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/racunovodstvo-preduzece:dev

      - name: Build and Push racunovodstvo-nabavka image
        uses: docker/build-push-action@v2
        with:
          context: ./nabavka
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/racunovodstvo-nabavka:dev

      - name: Build and Push racunovodstvo-user image
        uses: docker/build-push-action@v2
        with:
          context: ./user
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/racunovodstvo-user:dev
